name: Build and publish

on:
  push:
    branches:
      - github-actions

jobs:
  build:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: python -m build
      - name: Debug variables and secrets per environment
        run: |
          echo "VARS_ACTION_TEST: ${{ vars.ACTION_TEST_VARS }}"
          echo "SECR_ACTION_TEST: ${{ secrets.ACTIONS_TEST_SECRETS }}"
          echo "VARS_IN_TEST: ${{ vars.VARS_TEST_OR_PROD }}"
          echo "VARS_IN_PROD: ${{ vars.VARS_TEST_OR_PROD }}"
          echo "SECR_IN_TEST: ${{ secrets.SECRETS_TEST_OR_PROD }}"
          echo "SECR_IN_PROD: ${{ secrets.SECRETS_TEST_OR_PROD }}"
      # - name: Publish package
      #   uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      #   with: